--- #YAML:1.0
name:                CORBA-XMLSchemas
version:             2.61
abstract:            IDL compiler to WSDL/SOAP and W3C Schema
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.3201
distribution_type:   module
requires:     
    CORBA::IDL:                    2.6
    XML::DOM:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Francois PERRAD (francois.perrad@gadz.org)
