# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CORBA-XMLSchemas
version:      0.40
version_from: xsd.pm
installdirs:  site
requires:
    CORBA::IDL::node:              2.4
    XML::DOM:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
