# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CORBA-XMLSchemas
version:      2.60
version_from: lib/CORBA/XMLSchemas.pm
installdirs:  site
requires:
    CORBA::IDL:                    2.6
    XML::DOM:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
